# Generated by Django 3.2.7 on 2021-09-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('cel', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('fbid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('available', models.DateTimeField()),
                ('lts', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='fb_avida.client')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='fb_avida.orderstage')),
            ],
        ),
        migrations.CreateModel(
            name='DiscardedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('available', models.DateTimeField(null=True)),
                ('lts', models.IntegerField()),
                ('discarded', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discarded_order', to='fb_avida.client')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discarded_order', to='fb_avida.orderstage')),
            ],
        ),
    ]
